name: pinch_zoom_release_unzoom
description: A Widget to let you have a pinch to zoom that returns to the old size after the pinch has ended. Is very similar to the way you can zoom pictures on instagram
version: 2.0.0
homepage: https://incaview.com
repository: https://github.com/ivofernandes/pinch_zoom_release_unzoom

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

